name: Update GitHub Stats
on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:       # Allows manual runs

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required to push changes
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git history

      - name: Generate stats
        uses: anuraghazra/github-readme-stats@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Your PAT goes here
        with:
          REPO_URL: https://github.com/supto11/supto11  # Your profile repo

      - name: Commit and push
        run: |
          git config user.name "Supto Purakayasto"
          git config user.email "codersupto@gmail.com"
          git add README.md
          git commit -m "📈 Auto-update GitHub stats [skip ci]"
          git push
